import time
import re


def base_searcher(words, pattern):
    pattern_words = []
    start = time.time()
    for word in words:
        for pat in pattern:
            if pat in word:
                pattern_words.append(word)
    duration = time.time() - start
    return duration, pattern_words


def find_searcher(words, pattern):
    pattern_words = []
    start = time.time()
    for word in words:
        for pat in pattern:
            if word.find(pat) != -1:
                pattern_words.append(word)
    duration = time.time() - start
    return duration, pattern_words


def regex_searcher(words, pattern):
    pattern_words = []
    start = time.time()
    for word in words:
        for pat in pattern:
            if re.search(r'\{}'.format(pat), word):
                pattern_words.append(word)
    duration = time.time() - start
    return duration, pattern_words

# I looked for this kind of dataset but couldn't find one.  Google fu too weak.
cross = {
    "ziplock":["plastic"],
    "yucca":["organic"],
    "wrapping":["plastic", "paper"],
    "wrappers":["plastic"],
    "wrap":["plastic"],
    "wood":["construction", "organic"],
    "wire":["metal"],
    "wine":["glass"],
    "window":["construction", "glass"],
    "windows":["construction", "glass"],
    "wax":["organic"],
    "waste":["organic"],
    "vinyl":["construction", "plastic"],
    "vinegar":["organic"],
    "vegetable":["organic"],
    "vegetables":["organic"],
    "vases":["construction", "ceramic"],
    "tyvek":["construction", "plastic"],
    "twine":["construction", "organic"],
    "tv":["electronic"],
    "tvs":["electronic"],
    "tupperware":["plastic"],
    "ubcs":["res-evil"],
    "tuna":["organic"],
    "tubing":["construction", "plastic"],
    "trimmings":["organic"],
    "trays":["metal"],
    "transparencies":["plastic"],
    "toys":["plastic"],
    "towel":["organic"],
    "towels":["organic"],
    "toxic":["chemical"],
    "totes":["organic"],
    "toothpaste":["chemical"],
    "toilet":["ceramic"],
    "toner":["chemical", "printer"],
    "tissue":["organic"],
    "tissues":["organic"],
    "tin":["metal"],
    "tins":["metal"],
    "textbooks":["organic"],
    "text":["organic"],
    "telephone":["electronic"],
    "tea":["organic"],
    "tarps":["construction", "plastic"],
    "tanks":["plastic", "metal"],
    "syrub":["organic"],
    "syringes":["danger"],
    "styrofoam":["plastic", "unrecyclable"],
    "string":["organic"],
    "strings":["organic"],
    "straws":["plastic", "organic"],
    "strawberry":["organic"],
    "stickers":["plastic"],
    "steel":["metal"],
    "steels":["metal"],
    "stainless":["metal"],
    "soup":["organic", "chemical"],
    "solution":["chemical"],
    "softener":["chemical"],
    "softball":["plastic"],
    "soda":["glass", "organic"],
    "soap":["chemical"],
    "slick":["chemical"],
    "skillets":["metal"],
    "silverware":["metal"],
    "silage":["organic", "metal"],
    "siding":["construction"],
    "shrink":["plastic", "construction"],
    "shoes":["organic", "plastic"],
    "shingles":["construction"],
    "sharps":["chemical", "danger"],
    "shampoo":["chemical", "plastic"],
    "screws":["metal"],
    "salad":["organic"],
    "rubber":["chemical", "construction"],
    "rope":["organic"],
    "rolls":["plastic", "metal"],
    "rock":["construction"],
    "razors":["metal", "danger"],
    "pyrex":["glass"],
    "pvc":["plastic"],
    "pudding":["organic"],
    "propane":["metal", "chemical", "danger"],
    "produce":["organic"],
    "printouts":["plastic"],
    "printer":["printer"],
    "pringles":["paper"],
    "pressurized":["metal", "danger"],
    "pottery":["ceramic"],
    "pots":["ceramic"],
    "postcards":["paper"],
    "popcorn":["organic"],
    "polystyrene":["plastic"],
    "polypropylene":["plastic"],
    "polymer":["plastic"],
    "poly":["plastic"],
    "plates":["ceramic"],
    "plugs":["ceramic"],
    "plastics":["plastic"],
    "plasticcontainers":["plastic"],
    "plastic":["plastic"],
    "planter":["ceramic", "organic"],
    "plant":["organic"],
    "pizza":["organic"],
    "pipes":["metal", "plastic", "construction"],
    "pie":["organic"],
    "pickles":["organic", "glass"],
    "photographs":["plastic"],
    "phones":["electronic"],
    "pete":["plastic"],
    "pet":["plastic", "organic"],
    "pesticides":["chemical"],
    "pesticide":["chemical"],
    "peanuts":["organic"],
    "pasta":["organic"],
    "paper":["paper"],
    "paperback":["paper"],
    "paperboard":["paper"],
    "pans":["metal"],
    "palm":["organic", "metal"],
    "paint":["chemical"],
    "page":["paper"],
    "packing":["paper", "plastic"],
    "packaging":["paper", "plastic"],
    "oxygen":["metal", "danger"],
    "ovenware":["ceramic"],
    "oil":["chemical", "organic"],
    "oils":["chemical", "organic"],
    "notebook":["paper"],
    "notebooks":["paper"],
    "novels":["paper"],
    "notes":["paper"],
    "newsprint":["paper"],
    "newspapers":["paper"],
    "newspaper":["paper"],
    "needles":["danger"],
    "napkins":["organic"],
    "nails":["organic", "metal", "construction"],
    "mugs":["ceramic"],
    "motor":["chemical"],
    "mirrors":["glass"],
    "milk":["organic"],
    "microwaves":["electronic"],
    "microwave":["electronic"],
    "metals":["metal"],
    "metallic":["metal"],
    "medications":["chemical"],
    "medicine":["chemical"],
    "meat":["organic"],
    "meats":["organic"],
    "margarine":["organic"],
    "manuals":["paper"],
    "manila":["paper"],
    "mail":["paper"],
    "magazines":["paper"],
    "machinery":["metal"],
    "livestock":["metal"],
    "liquor":["glass"],
    "leave":["organic"],
    "lighbulbs":["chemical", "glass"],
    "linens":["organic"],
    "lids":["plastic","glass"],
    "leaded":["metal", "danger"],
    "ldpe":["plastic"],
    "laundry":["organic"],
    "kleenex":["organic"],
    "ketchup":["organic", "plastic", "glass"],
    "kerosene":["metal", "chemical", "danger"],
    "jug":["plastic", "ceramic"],
    "jugs":["plastic", "ceramic"],
    "jars":["plastic", "ceramic", "glass"],
    "jar":["plastic", "ceramic", "glass"],
    "iron":["metal"],
    "insulation":["construction"],
    "inkjet":["printer"],
    "hose":["plastic"],
    "herbicide":["chemical"],
    "hdpe":["plastic"],
    "hazardous":["danger"],
    "hairspray":["metal", "danger"],
    "grease":["organic"],
    "grass":["organic"],
    "glasses":["glass"],
    "gasoline":["chemical", "danger"],
    "gas":["chemical", "danger"],
    "fuel":["chemical", "danger"],
    "fruit":["organic"],
    "fronds":["organic", "metal"],
    "freon":["chemical", "metal"],
    "forks":["metal"],
    "food":["organic"],
    "foil":["metal"],
    "foam":["plastic"],
    "fluorescent":["chemical", "glass"],
    "flowerpots":["ceramic"],
    "flower":["organic"],
    "flooring":["construction", "plastic"],
    "flatware":["metal"],
    "flammable":["danger"],
    "filters":["chemical"],
    "filter":["chemical"],
    "fiberboard":["construction"],
    "fertilizer":["chemical", "danger"],
    "fencing":["construction"],
    "fax":["electronic"],
    "fabric":["organic", "plastic"],
    "envelopes":["paper"],
    "electronic":["electronic"],
    "electronics":["electronic"],
    "electrical":["electronic"],
    "electric":["electronic"],
    "egg":["organic"],
    "egcartons":["paper"],
    "dvds":["glass", "plastic"],
    "drink":["glass"],
    "drinks":["glass"],
    "dishes":["ceramic"],
    "dish":["ceramic"],
    "detergent":["chemical"],
    "detegnts":["chemical"],
    "detegnt":["chemical"],
    "debris":["construction"],
    "dairy":["organic"],
    "crystal":["glass"],
    "corrugated":["metal"],
    "corn":["organic"],
    "cookware":["ceramic"],
    "contaminated":["danger"],
    "concrete":["construction"],
    "clothing":["organic"],
    "chemical":["chemical"],
    "chemicals":["chemical"],
    "cheese":["organic"],
    "ceramic":["ceramic"],
    "ceramics":["ceramic"],
    "cartridges":["danger"],
    "carton":["paper", "plastic"],
    "cartons":["paper", "plastic"],
    "cardboard":["paper"],
    "canister":["metal"],
    "buckets":["plastic", "metal"],
    "brick":["construction"],
    "brass":["metal"],
    "bowls":["ceramic"],
    "bottle":["glass"],
    "bottles":["glass"],
    "booklets":["paper"],
    "bleach":["chemical"],
    "bikes":["metal"],
    "batteries":["electronic", "metal", "danger", "chemical"],
    "bags":["plastic"],
    "baggies":["plastic"],
    "bag":["plastic"],
    "automotive":["chemical"],
    "aseptic":["chemical", "danger"],
    "antifreeze":["chemical", "danger"],
    "aluminum":["metal"],
    "aerosols":["metal"],
    "aerosol":["metal"],
    "1":["plastic"],
    "2":["plastic"],
    "3":["plastic"],
    "4":["plastic"],
    "5":["plastic"],
    "6":["plastic"],
    "7":["plastic"]
}



